# Change these first
owner: Incognitus-Io # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://incognitus.io
  - name: Management Console
    url: https://incognitus.io/manage

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.incognitus.io
  logoUrl: https://incognitus.io/img/incognitus-logo-dark.png
  name: Incognitus
  introTitle: "**Incognitus** feature flag platform."
  introMessage: This is the status page which uses **real-time** data about the platforms status and uptime
  navbar:
    - title: Status
      href: /
    - title: Incognitus
      href: https://incognitus.io
      
commitMessage:
  commitAuthorName: "Incognitus Status Bot"
  commitAuthorEmail: "Status@incognitus.io"
   
notifications:
  - type: slack
    channel: C6VP3KA1E

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
